# Generated by Django 4.2.13 on 2026-06-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='products',
        ),
        migrations.CreateModel(
            name='PackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_products', to='core.pack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_products', to='core.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('pack', 'product')},
            },
        ),
    ]
