COMMERCE_DATA = {
    "productCollections": [
        {
            "title": "CLEAR",
            "badge": "Invisible • Sommeil • Confort",
            "badgeClass": "from-[#2563EB] to-[#25D8FF]",
            "accent": "#25D8FF",
            "glowClass": "bg-[#25D8FF]/35",
            "borderHover": "hover:border-[#25D8FF]/55",
            "shadowHover": "hover:shadow-[0_28px_80px_rgba(37,216,255,0.18)]",
            "buttonClass": "from-[#2563EB] to-[#25D8FF] shadow-[0_16px_42px_rgba(37,216,255,0.24)] hover:shadow-[0_20px_52px_rgba(37,216,255,0.38)]",
            "products": [
                {
                    "id": "clear-26",
                    "name": "CLEAR 26",
                    "quantity": "26 bandes",
                    "price": "159 DH",
                    "priceValue": 159,
                    "description": "Découverte",
                    "image": "/images/breathe-right-extra-strength-clear-26.jpg",
                },
                {
                    "id": "clear-30",
                    "name": "CLEAR 30",
                    "quantity": "30 bandes",
                    "price": "179 DH",
                    "priceValue": 179,
                    "description": "Routine mensuelle",
                    "badge": "Le plus populaire",
                    "image": "/images/breathe-right-clear-small-medium-30.jpg",
                },
                {
                    "id": "clear-44",
                    "name": "CLEAR 44",
                    "quantity": "44 bandes",
                    "price": "219 DH",
                    "priceValue": 219,
                    "description": "Stock confort",
                    "label": "Meilleur rapport qualité/prix",
                    "image": "/images/breathe-right-extra-strength-clear-44.jpg",
                },
            ],
        },
        {
            "title": "TAN",
            "badge": "Sport • Performance",
            "badgeClass": "from-[#FF5A3D] to-[#FF9B55]",
            "accent": "#FF7A45",
            "glowClass": "bg-[#FF7A45]/32",
            "borderHover": "hover:border-[#FF7A45]/55",
            "shadowHover": "hover:shadow-[0_28px_80px_rgba(255,122,69,0.16)]",
            "buttonClass": "from-[#FF5A3D] to-[#FF9B55] shadow-[0_16px_42px_rgba(255,122,69,0.22)] hover:shadow-[0_20px_52px_rgba(255,122,69,0.34)]",
            "products": [
                {
                    "id": "tan-26",
                    "name": "TAN 26",
                    "quantity": "26 bandes",
                    "price": "159 DH",
                    "priceValue": 159,
                    "description": "Découverte",
                    "image": "/images/breathe-right-extra-strength-tan-26.jpg",
                },
                {
                    "id": "tan-30",
                    "name": "TAN 30",
                    "quantity": "30 bandes",
                    "price": "179 DH",
                    "priceValue": 179,
                    "description": "Routine sportive",
                    "badge": "Le plus populaire",
                    "image": "/images/breathe-right-tan-large-30.jpg",
                },
                {
                    "id": "tan-44",
                    "name": "TAN 44",
                    "quantity": "44 bandes",
                    "price": "219 DH",
                    "priceValue": 219,
                    "description": "Performance durable",
                    "label": "Meilleur rapport qualité/prix",
                    "image": "/images/breathe-right-extra-strength-tan-44.jpg",
                },
            ],
        },
    ],
    "curatedPacks": [
        {
            "id": "pack-duo",
            "title": "Pack Duo",
            "description": "Le meilleur équilibre entre sommeil et performance.",
            "price": "300 DH",
            "priceValue": 300,
            "cta": "Ajouter au panier",
            "accent": "#25D8FF",
            "glowClass": "bg-[#25D8FF]/36",
            "borderHover": "hover:border-[#25D8FF]/55",
            "shadowHover": "hover:shadow-[0_30px_90px_rgba(37,216,255,0.18)]",
            "buttonClass": "from-[#2563EB] to-[#25D8FF] shadow-[0_16px_42px_rgba(37,216,255,0.24)] hover:shadow-[0_20px_54px_rgba(37,216,255,0.38)]",
            "includes": ["1 boîte CLEAR (26)", "1 boîte TAN (26)", "Livraison incluse"],
            "products": [
                {
                    "image": "/images/breathe-right-extra-strength-clear-26.jpg",
                    "alt": "Breatheex Clear 26 box",
                    "className": "left-[22%] top-[34px] z-10 h-[218px] w-[150px] -rotate-5",
                },
                {
                    "image": "/images/breathe-right-extra-strength-tan-26.jpg",
                    "alt": "Breatheex Tan 26 box",
                    "className": "right-[22%] top-[54px] z-20 h-[218px] w-[150px] rotate-5",
                },
            ],
        },
        {
            "id": "pack-sommeil",
            "title": "Pack Sommeil",
            "description": "Pour améliorer votre sommeil et réduire les ronflements chaque nuit.",
            "price": "349 DH",
            "priceValue": 349,
            "cta": "Ajouter au panier",
            "accent": "#25D8FF",
            "glowClass": "bg-[#25D8FF]/34",
            "borderHover": "hover:border-[#25D8FF]/55",
            "shadowHover": "hover:shadow-[0_30px_90px_rgba(37,216,255,0.16)]",
            "buttonClass": "from-[#0EA5E9] to-[#25D8FF] shadow-[0_16px_42px_rgba(37,216,255,0.22)] hover:shadow-[0_20px_54px_rgba(37,216,255,0.34)]",
            "includes": ["2 boîtes CLEAR (30)", "Livraison incluse", "Confort quotidien"],
            "products": [
                {
                    "image": "/images/breathe-right-clear-small-medium-30.jpg",
                    "alt": "Breatheex Clear 30 box",
                    "className": "left-[22%] top-[34px] z-10 h-[220px] w-[152px] -rotate-4",
                },
                {
                    "image": "/images/breathe-right-clear-small-medium-30.jpg",
                    "alt": "Breatheex Clear 30 box",
                    "className": "right-[22%] top-[54px] z-20 h-[220px] w-[152px] rotate-4",
                },
            ],
        },
        {
            "id": "pack-performance",
            "title": "Pack Performance",
            "description": "Conçu pour le sport, les entraînements et les activités intensives.",
            "price": "349 DH",
            "priceValue": 349,
            "cta": "Ajouter au panier",
            "accent": "#FF7A45",
            "glowClass": "bg-[#FF7A45]/34",
            "borderHover": "hover:border-[#FF7A45]/55",
            "shadowHover": "hover:shadow-[0_30px_90px_rgba(255,122,69,0.16)]",
            "buttonClass": "from-[#FF5A3D] to-[#FF9B55] shadow-[0_16px_42px_rgba(255,122,69,0.22)] hover:shadow-[0_20px_54px_rgba(255,122,69,0.34)]",
            "includes": ["2 boîtes TAN (30)", "Livraison incluse", "Maintien renforcé"],
            "products": [
                {
                    "image": "/images/breathe-right-tan-large-30.jpg",
                    "alt": "Breatheex Tan 30 box",
                    "className": "left-[22%] top-[34px] z-10 h-[220px] w-[152px] -rotate-4",
                },
                {
                    "image": "/images/breathe-right-tan-large-30.jpg",
                    "alt": "Breatheex Tan 30 box",
                    "className": "right-[22%] top-[54px] z-20 h-[220px] w-[152px] rotate-4",
                },
            ],
        },
        {
            "id": "pack-annuel",
            "title": "Pack Annuel",
            "description": "Une année complète de respiration optimale pour toute la famille.",
            "price": "699 DH",
            "priceValue": 699,
            "cta": "Ajouter au panier",
            "accent": "#D97706",
            "glowClass": "bg-[#FACC15]/34",
            "borderHover": "hover:border-[#FACC15]/70",
            "shadowHover": "hover:shadow-[0_30px_90px_rgba(217,119,6,0.16)]",
            "buttonClass": "from-[#D97706] via-[#F59E0B] to-[#FACC15] shadow-[0_16px_42px_rgba(217,119,6,0.22)] hover:shadow-[0_20px_54px_rgba(217,119,6,0.34)]",
            "includes": ["4 boîtes (44)", "CLEAR + TAN", "Livraison incluse"],
            "products": [
                {
                    "image": "/images/breathe-right-extra-strength-clear-44.jpg",
                    "alt": "Breatheex Clear 44 box",
                    "className": "left-[12%] top-[74px] z-10 h-[170px] w-[120px] -rotate-8",
                },
                {
                    "image": "/images/breathe-right-extra-strength-tan-44.jpg",
                    "alt": "Breatheex Tan 44 box",
                    "className": "right-[12%] top-[74px] z-10 h-[170px] w-[120px] rotate-8",
                },
                {
                    "image": "/images/breathe-right-extra-strength-clear-44.jpg",
                    "alt": "Breatheex Clear 44 box",
                    "className": "left-[24%] top-[28px] z-20 h-[205px] w-[145px] -rotate-3",
                },
                {
                    "image": "/images/breathe-right-extra-strength-tan-44.jpg",
                    "alt": "Breatheex Tan 44 box",
                    "className": "right-[24%] top-[38px] z-30 h-[205px] w-[145px] rotate-3",
                },
            ],
        },
    ],
    "commerceTrustItems": [
        {"label": "Livraison incluse", "iconName": "truck"},
        {"label": "Paiement à la livraison", "iconName": "credit-card"},
        {"label": "Produit officiel", "iconName": "shield-check"},
        {"label": "Support WhatsApp", "iconName": "message-circle"},
    ],
}
